global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [
        'prometheus:9090',
#               'localhost:9090',
#               '127.0.0.1:9090',
        'host.docker.internal:9090'
      ]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [
#        'cadvisor:8080'
         'host.docker.internal:8080'
      ]


  - job_name: 'node-exporter'
    static_configs:
      - targets: [
        'host.docker.internal:9100',
#        'localhost:9100'
#        'node-exporter:9100'
      ]

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [
#        'pushgateway:9091'
        'host.docker.internal:9091'
      ]



alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [
          "alertmanager:9093"
        ]



